export const ROUTE_MANIFEST = {
  HOME: 'Home',
  EXPLORE: 'Explore',
  STEM_ACTIVITIES: 'STEM Activities',
  STEM_ACTIVITY_DETAIL: 'STEM Activity Detail',
  STEM_PROGRESS: 'STEM Progress',
  COMMAND_CENTER: 'Command Center',
  LAUNCHES: 'Launches',
  SKY_EVENTS: 'Sky Events',
  COMETS: 'Comets',
  SOLAR_MAP: 'Solar Map',
  STREAMS: 'Streams',
  PLANETS: 'Visit Another Planet',
  BEYOND: 'Beyond Our Solar System',
  MISSION_ALERTS: 'Mission Alerts',
  ROCKETS: 'Rockets',
  MISSIONS_BRIEFING: 'Mission Briefing',
}
