export const ROUTE_MANIFEST = {
  HOME: 'Home',
  EXPLORE: 'Explore',
  LEARNING: 'Learning',
  LEARNING_STEM: 'Learning STEM',
  LEARNING_CYBERLAB: 'Learning Cyber Lab',
  STEM_ACTIVITIES: 'STEM Activities',
  STEM_ACTIVITY_DETAIL: 'STEM Activity Detail',
  STEM_PROGRESS: 'STEM Progress',
  COMMAND_CENTER: 'Command Center',
  LAUNCHES: 'Launches',
  SKY_EVENTS: 'Sky Events',
  COMETS: 'Comets',
  SOLAR_MAP: 'Solar Map',
  STREAMS: 'Streams',
  PLANETS: 'Visit Another Planet',
  BEYOND: 'Beyond Our Solar System',
  MISSION_ALERTS: 'Mission Alerts',
  ROCKETS: 'Rockets',
  ROCKET_DETAIL: 'Rocket Detail',
  SPACECRAFT_HUB: 'Spacecraft Hub',
  SPACECRAFT_DETAIL: 'Spacecraft Detail',
  COMET: 'C.O.M.E.T.',
  LUNAR_EVENTS: 'Lunar Events',
  PROFILE: 'Profile',
  UPDATES_HUB: 'Updates Hub',
  UPDATES_NEWS: 'Updates News',
  UPDATES_BLOG: 'Updates Blog',
  UPDATES_OFFICIAL: 'Updates Official',
  UPDATES_LIVE: 'Updates Live',
  UPDATES_X: 'Updates X',
  PLANET_DETAIL: 'Planet Detail',
  MISSIONS_BRIEFING: 'Mission Briefing',
}
