// src/config/missions/artemis.js
// Artemis Program configuration for mission control dashboard
// Data-driven architecture for easy updates and expansion

export const ARTEMIS_PROGRAM = {
  id: 'artemis',
  name: 'ARTEMIS PROGRAM',
  subtitle: 'Human return to the Moon | Deep space operations | Gateway preparation',
  status: 'ACTIVE',
  leadAgency: 'NASA',
  primaryRocket: 'Space Launch System (SLS)',
  crewVehicle: 'Orion',
  destination: 'Lunar Orbit / Surface',
  firstMission: 'ARTEMIS I (COMPLETED)',
  description: 'NASA\'s Artemis program will land the first woman and first person of color on the Moon, using innovative technologies to explore more of the lunar surface than ever before.',
}

export const ARTEMIS_IMAGES = {
  slsLaunch: {
    url: '/images/artemis/sls-launch.jpg',
    alt: 'Artemis I SLS Launch',
    caption: 'Space Launch System lifts off from Kennedy Space Center',
    credit: 'NASA/Joel Kowsky',
  },
  orionEarth: {
    url: '/images/artemis/orion-earth.jpg',
    alt: 'Orion spacecraft with Earth and Moon',
    caption: 'Orion at maximum distance from Earth during Artemis I',
    credit: 'NASA',
  },
}

export const ARTEMIS_ROCKETS = {
  sls: {
    id: 'sls',
    name: 'Space Launch System (SLS)',
    manufacturer: 'Boeing / Northrop Grumman / Aerojet Rocketdyne',
    type: 'Super Heavy-Lift Launch Vehicle',
    configurations: {
      block1: {
        name: 'Block 1',
        payload_leo: '95,000 kg',
        payload_tli: '27,000 kg',
        thrust: '39,100 kN',
        height: '98 m',
        stages: 2,
        boosters: '2x Solid Rocket Boosters',
        missions: ['Artemis I', 'Artemis II', 'Artemis III'],
      },
      block1b: {
        name: 'Block 1B',
        payload_leo: '105,000 kg',
        payload_tli: '42,000 kg',
        thrust: '39,100 kN',
        height: '111 m',
        stages: 2,
        boosters: '2x Solid Rocket Boosters',
        upperStage: 'Exploration Upper Stage (EUS)',
        missions: ['Artemis IV+'],
      },
    },
    firstFlight: 'November 16, 2022',
    status: 'OPERATIONAL',
  },
}

export const ARTEMIS_SPACECRAFT = {
  orion: {
    id: 'orion',
    name: 'Orion Multi-Purpose Crew Vehicle',
    manufacturer: 'Lockheed Martin',
    type: 'Crew Capsule',
    crewCapacity: 4,
    missionDuration: '21 days (independent) / 6 months (docked)',
    serviceModule: 'European Service Module (ESM)',
    serviceModuleProvider: 'ESA / Airbus',
    heatShield: 'AVCOAT ablative heat shield',
    reentrySpeed: '40,000 km/h',
    capabilities: [
      'Deep space crew transport',
      'Lunar orbit operations',
      'Gateway docking',
      'Earth re-entry from lunar return trajectory',
    ],
    status: 'OPERATIONAL',
  },
  hls: {
    id: 'hls',
    name: 'Human Landing System (Starship HLS)',
    manufacturer: 'SpaceX',
    type: 'Lunar Lander',
    crewCapacity: 2,
    capabilities: [
      'Lunar surface descent',
      'Surface operations support',
      'Lunar ascent to orbit',
      'Orion docking',
    ],
    status: 'IN DEVELOPMENT',
  },
  gateway: {
    id: 'gateway',
    name: 'Lunar Gateway',
    type: 'Space Station',
    orbit: 'Near-Rectilinear Halo Orbit (NRHO)',
    modules: [
      { name: 'PPE', fullName: 'Power and Propulsion Element', provider: 'Maxar' },
      { name: 'HALO', fullName: 'Habitation and Logistics Outpost', provider: 'Northrop Grumman' },
      { name: 'I-HAB', fullName: 'International Habitation Module', provider: 'ESA / JAXA' },
    ],
    capabilities: [
      'Crew habitation',
      'Lunar surface mission staging',
      'Deep space research',
      'Mars mission preparation',
    ],
    status: 'IN DEVELOPMENT',
  },
}

export const ARTEMIS_SYSTEMS = [
  {
    id: 'navigation',
    name: 'Navigation & Guidance',
    description: 'Advanced inertial navigation with star tracker and GPS backup for cislunar operations.',
    importance: 'Enables precise trajectory corrections for lunar orbit insertion and Earth return.',
  },
  {
    id: 'life-support',
    name: 'Life Support (ECLSS)',
    description: 'Environmental Control and Life Support System providing atmosphere, water, and thermal regulation.',
    importance: 'Sustains crew for up to 21 days in deep space without resupply.',
  },
  {
    id: 'power',
    name: 'Power Systems',
    description: 'Solar array wings on European Service Module generating 11 kW of electrical power.',
    importance: 'Powers all spacecraft systems including propulsion, life support, and communications.',
  },
  {
    id: 'communications',
    name: 'Communications',
    description: 'S-band and Ka-band systems with Deep Space Network compatibility.',
    importance: 'Maintains continuous contact with Earth at lunar distances (384,400 km).',
  },
  {
    id: 'heat-shield',
    name: 'Heat Shield',
    description: 'AVCOAT ablative heat shield rated for lunar return velocities.',
    importance: 'Protects crew during re-entry at 40,000 km/h, the fastest human re-entry ever.',
  },
  {
    id: 'propulsion',
    name: 'Propulsion',
    description: 'Orbital Maneuvering System engine with 33 auxiliary thrusters.',
    importance: 'Provides trajectory corrections, lunar orbit insertion, and trans-Earth injection.',
  },
]

export const ARTEMIS_KNOWLEDGE = [
  {
    id: 'why-return',
    title: 'Why Return to the Moon?',
    content: 'The Moon serves as a proving ground for deep space exploration technologies. Artemis will establish sustainable lunar presence, test systems for Mars missions, and unlock scientific discoveries about the Moon\'s south pole water ice deposits.',
  },
  {
    id: 'apollo-difference',
    title: 'How Artemis Differs from Apollo',
    content: 'Unlike Apollo\'s flags-and-footprints approach, Artemis aims for sustainable presence. Key differences include: international partnerships, commercial providers, Gateway station, south pole landing sites, and technology development for Mars.',
  },
  {
    id: 'gateway-overview',
    title: 'Lunar Gateway Overview',
    content: 'Gateway is a small space station in lunar orbit serving as a staging point for lunar surface missions. It will orbit the Moon in a near-rectilinear halo orbit, providing access to the entire lunar surface over time.',
  },
  {
    id: 'mars-preparation',
    title: 'Mars Preparation Role',
    content: 'Artemis serves as a testbed for Mars mission technologies including: long-duration life support, deep space navigation, radiation protection, and crew health monitoring. Lessons learned will directly inform Mars mission architecture.',
  },
]

export const ARTEMIS_MISSIONS = [
  {
    id: 'artemis-1',
    name: 'ARTEMIS I',
    status: 'COMPLETED',
    missionType: 'Uncrewed Test Flight',
    summary: 'First integrated flight test of SLS and Orion, sending an uncrewed spacecraft around the Moon to validate systems for future crewed missions.',
    launchDate: 'November 16, 2022',
    splashdownDate: 'December 11, 2022',
    duration: '25 days, 10 hours, 53 minutes',
    rocket: 'sls',
    rocketConfig: 'block1',
    spacecraft: ['orion'],
    lander: null,
    gateway: false,
    crew: null,
    dates: {
      launchWindow: 'November 16, 2022',
      milestones: [
        { date: 'Nov 16, 2022', event: 'Launch from Kennedy Space Center' },
        { date: 'Nov 21, 2022', event: 'Outbound powered flyby' },
        { date: 'Nov 25, 2022', event: 'Distant retrograde orbit insertion' },
        { date: 'Dec 1, 2022', event: 'DRO departure burn' },
        { date: 'Dec 5, 2022', event: 'Return powered flyby' },
        { date: 'Dec 11, 2022', event: 'Splashdown in Pacific Ocean' },
      ],
    },
    objectives: [
      'Validate Orion spacecraft systems in deep space environment',
      'Demonstrate SLS performance and reliability',
      'Test heat shield at lunar return velocities (40,000 km/h)',
      'Verify Orion recovery operations',
      'Collect flight data for crewed mission certification',
    ],
    achievements: [
      'Farthest distance traveled by human-rated spacecraft: 432,210 km',
      'Successful lunar flyby and distant retrograde orbit',
      'Heat shield performed nominally at re-entry',
      'All primary mission objectives achieved',
    ],
    highlights: [
      { label: 'Distance from Earth', value: '432,210 km' },
      { label: 'Lunar Flybys', value: '2' },
      { label: 'Orbit Type', value: 'Distant Retrograde Orbit' },
      { label: 'Splashdown Location', value: 'Pacific Ocean' },
    ],
    facts: [
      'Orion traveled farther than any spacecraft built for humans has ever flown.',
      'The heat shield experienced temperatures of approximately 5,000°F during re-entry.',
      'Mannequins named Commander Moonikin Campos, Helga, and Zohar collected radiation data.',
      'The mission tested the Callisto technology demonstration with Amazon Alexa and Cisco Webex.',
    ],
  },
  {
    id: 'artemis-2',
    name: 'ARTEMIS II',
    status: 'PLANNED',
    missionType: 'Crewed Lunar Flyby',
    summary: 'First crewed Artemis mission, sending four astronauts on a lunar flyby to test Orion life support systems and validate crew operations in deep space.',
    targetLaunch: 'September 2025',
    duration: '~10 days',
    rocket: 'sls',
    rocketConfig: 'block1',
    spacecraft: ['orion'],
    lander: null,
    gateway: false,
    dates: {
      launchWindow: 'September 2025',
      milestones: [
        { date: 'T+0', event: 'Launch from Kennedy Space Center' },
        { date: 'T+2h', event: 'Trans-lunar injection burn' },
        { date: 'T+4 days', event: 'Lunar flyby (~10,000 km altitude)' },
        { date: 'T+10 days', event: 'Earth re-entry and splashdown' },
      ],
    },
    crew: {
      status: 'ASSIGNED',
      size: 4,
      members: [
        {
          name: 'Reid Wiseman',
          role: 'Commander',
          agency: 'NASA',
          country: 'USA',
          previousMissions: ['Expedition 40/41'],
        },
        {
          name: 'Victor Glover',
          role: 'Pilot',
          agency: 'NASA',
          country: 'USA',
          previousMissions: ['Crew-1', 'Expedition 64'],
        },
        {
          name: 'Christina Koch',
          role: 'Mission Specialist',
          agency: 'NASA',
          country: 'USA',
          previousMissions: ['Expedition 59/60/61'],
        },
        {
          name: 'Jeremy Hansen',
          role: 'Mission Specialist',
          agency: 'CSA',
          country: 'CAN',
          previousMissions: [],
        },
      ],
    },
    objectives: [
      'First crewed flight of Orion spacecraft',
      'First crewed flight of SLS rocket',
      'Validate life support systems with crew aboard',
      'Demonstrate crew operations in deep space',
      'Lunar flyby trajectory verification',
    ],
    highlights: [
      { label: 'Crew Size', value: '4 astronauts' },
      { label: 'Mission Type', value: 'Free-return trajectory' },
      { label: 'First Canadian', value: 'Jeremy Hansen' },
      { label: 'Lunar Distance', value: '~10,000 km from surface' },
    ],
    facts: [
      'This will be the first crewed mission beyond low Earth orbit since Apollo 17 in 1972.',
      'Christina Koch holds the record for longest single spaceflight by a woman (328 days).',
      'Jeremy Hansen will become the first Canadian to travel beyond low Earth orbit.',
      'The crew will manually pilot Orion for portions of the mission to test handling qualities.',
    ],
  },
  {
    id: 'artemis-3',
    name: 'ARTEMIS III',
    status: 'PLANNED',
    missionType: 'Crewed Lunar Landing',
    summary: 'Historic return to the lunar surface, landing the first woman and first person of color on the Moon near the south pole using SpaceX Starship HLS.',
    targetLaunch: '2026',
    duration: '~30 days',
    rocket: 'sls',
    rocketConfig: 'block1',
    spacecraft: ['orion', 'hls'],
    lander: 'hls',
    gateway: false,
    dates: {
      launchWindow: '2026',
      milestones: [
        { date: 'Pre-mission', event: 'Starship HLS pre-positioned in lunar orbit' },
        { date: 'T+0', event: 'SLS/Orion launch from Kennedy Space Center' },
        { date: 'T+4 days', event: 'Orion docks with Starship HLS in lunar orbit' },
        { date: 'T+5 days', event: 'Two crew members descend to lunar surface' },
        { date: 'T+12 days', event: 'Surface operations and EVAs complete' },
        { date: 'T+13 days', event: 'Ascent and Orion rendezvous' },
        { date: 'T+30 days', event: 'Earth re-entry and splashdown' },
      ],
    },
    crew: {
      status: 'TBD',
      size: 4,
      landingCrew: 2,
      members: null,
    },
    objectives: [
      'First crewed lunar landing since Apollo 17 (1972)',
      'First woman on the lunar surface',
      'First person of color on the lunar surface',
      'South pole region exploration',
      'Demonstrate Human Landing System (Starship HLS)',
      'Conduct lunar surface science operations',
    ],
    highlights: [
      { label: 'Landing Site', value: 'Lunar South Pole Region' },
      { label: 'Surface Time', value: '~6.5 days' },
      { label: 'EVAs Planned', value: '2+' },
      { label: 'Lander', value: 'SpaceX Starship HLS' },
    ],
    facts: [
      'The south pole region contains permanently shadowed craters with water ice deposits.',
      'Starship HLS will be the tallest lunar lander ever built at approximately 50 meters.',
      'Astronauts will use new xEMU spacesuits designed for lunar surface mobility.',
      'This will be the first lunar landing using commercial hardware under NASA contract.',
    ],
  },
  {
    id: 'artemis-4',
    name: 'ARTEMIS IV',
    status: 'PLANNED',
    missionType: 'Gateway Assembly',
    summary: 'First crewed mission to the Lunar Gateway station, delivering the I-HAB module and establishing a permanent human presence in lunar orbit.',
    targetLaunch: '2028',
    duration: '~30 days',
    rocket: 'sls',
    rocketConfig: 'block1b',
    spacecraft: ['orion', 'gateway'],
    lander: null,
    gateway: true,
    dates: {
      launchWindow: '2028',
      milestones: [
        { date: 'Pre-mission', event: 'Gateway PPE+HALO modules already in lunar orbit' },
        { date: 'T+0', event: 'SLS Block 1B launch with Orion and I-HAB' },
        { date: 'T+4 days', event: 'Orion arrives at Gateway in NRHO' },
        { date: 'T+5 days', event: 'I-HAB module installation begins' },
        { date: 'T+20 days', event: 'Gateway systems checkout complete' },
        { date: 'T+30 days', event: 'Orion departs for Earth return' },
      ],
    },
    crew: {
      status: 'TBD',
      size: 4,
      members: null,
    },
    objectives: [
      'First crewed mission to Lunar Gateway',
      'Deliver I-HAB module to Gateway',
      'First use of SLS Block 1B configuration',
      'Establish Gateway as operational outpost',
      'Demonstrate long-duration lunar orbit operations',
    ],
    highlights: [
      { label: 'Gateway Module', value: 'I-HAB delivery' },
      { label: 'SLS Config', value: 'Block 1B (first flight)' },
      { label: 'Orbit', value: 'Near-Rectilinear Halo Orbit' },
      { label: 'Station Partners', value: 'NASA, ESA, JAXA, CSA' },
    ],
    facts: [
      'Gateway will orbit the Moon in a near-rectilinear halo orbit, passing as close as 3,000 km.',
      'The I-HAB module is built by ESA and JAXA, marking international lunar cooperation.',
      'SLS Block 1B uses the more powerful Exploration Upper Stage for increased payload capacity.',
      'Gateway will serve as a staging point for future lunar surface missions.',
    ],
  },
]

export const MISSION_STATUS_COLORS = {
  COMPLETED: { bg: 'rgba(34, 197, 94, 0.2)', border: 'rgba(34, 197, 94, 0.5)', text: '#22c55e' },
  PLANNED: { bg: 'rgba(59, 130, 246, 0.2)', border: 'rgba(59, 130, 246, 0.5)', text: '#3b82f6' },
  ACTIVE: { bg: 'rgba(234, 179, 8, 0.2)', border: 'rgba(234, 179, 8, 0.5)', text: '#eab308' },
  'IN DEVELOPMENT': { bg: 'rgba(168, 85, 247, 0.2)', border: 'rgba(168, 85, 247, 0.5)', text: '#a855f7' },
  TBD: { bg: 'rgba(107, 114, 128, 0.2)', border: 'rgba(107, 114, 128, 0.5)', text: '#6b7280' },
  ASSIGNED: { bg: 'rgba(34, 197, 94, 0.2)', border: 'rgba(34, 197, 94, 0.5)', text: '#22c55e' },
}
