export const X_ACCOUNTS = [
  {
    id: 'x-nasa',
    name: 'NASA',
    handle: 'NASA',
    url: 'https://x.com/NASA',
    category: 'agency',
    priority: 1,
  },
  {
    id: 'x-esa',
    name: 'European Space Agency',
    handle: 'esa',
    url: 'https://x.com/esa',
    category: 'agency',
    priority: 2,
  },
  {
    id: 'x-spacex',
    name: 'SpaceX',
    handle: 'SpaceX',
    url: 'https://x.com/SpaceX',
    category: 'company',
    priority: 3,
  },
  {
    id: 'x-rocketlab',
    name: 'Rocket Lab',
    handle: 'RocketLab',
    url: 'https://x.com/RocketLab',
    category: 'company',
    priority: 4,
  },
  {
    id: 'x-nsf',
    name: 'NASASpaceflight (NSF)',
    handle: 'NASASpaceflight',
    url: 'https://x.com/NASASpaceflight',
    category: 'community',
    priority: 5,
  },
  {
    id: 'x-spaceflightnow',
    name: 'Spaceflight Now',
    handle: 'SpaceflightNow',
    url: 'https://x.com/SpaceflightNow',
    category: 'community',
    priority: 6,
  },
  {
    id: 'x-planet4589',
    name: 'Jonathan McDowell',
    handle: 'planet4589',
    url: 'https://x.com/planet4589',
    category: 'tracker',
    priority: 7,
  },
  {
    id: 'x-sciguyspace',
    name: 'Eric Berger',
    handle: 'SciGuySpace',
    url: 'https://x.com/SciGuySpace',
    category: 'journalist',
    priority: 8,
  },
  {
    id: 'x-nasaearth',
    name: 'NASA Earth',
    handle: 'NASAEarth',
    url: 'https://x.com/NASAEarth',
    category: 'agency',
    priority: 9,
  },
  {
    id: 'x-esaops',
    name: 'ESA Operations',
    handle: 'esaoperations',
    url: 'https://x.com/esaoperations',
    category: 'agency',
    priority: 10,
  },
]

export const X_CATEGORIES = [
  { id: 'all', label: 'All Accounts' },
  { id: 'agency', label: 'Space Agencies' },
  { id: 'company', label: 'Companies' },
  { id: 'community', label: 'Community' },
  { id: 'tracker', label: 'Trackers' },
  { id: 'journalist', label: 'Journalists' },
]
