export const YOUTUBE_CHANNELS = [
  {
    id: 'nasa',
    name: 'NASA',
    handle: '@NASA',
    channelId: 'UCLA_DiR1FfKNvjuUpBHmylQ',
    url: 'https://www.youtube.com/@NASA',
    focus: 'agency',
    priority: 1,
    description: 'Official NASA channel featuring launches, ISS activities, and mission coverage.',
  },
  {
    id: 'spacex',
    name: 'SpaceX',
    handle: '@SpaceX',
    channelId: 'UCtI0Hodo5o5dUb67FeUjDeA',
    url: 'https://www.youtube.com/@SpaceX',
    focus: 'launch',
    priority: 2,
    description: 'Official SpaceX channel with Falcon 9, Starship, and Dragon mission streams.',
  },
  {
    id: 'everyday-astronaut',
    name: 'Everyday Astronaut',
    handle: '@EverydayAstronaut',
    channelId: 'UC6uKrU_WqJ1R2HMTY3LIx5Q',
    url: 'https://www.youtube.com/@EverydayAstronaut',
    focus: 'creator',
    priority: 3,
    description: 'Making space exploration accessible through in-depth coverage of launches and rocket science.',
  },
  {
    id: 'nasaspaceflight',
    name: 'NASASpaceflight (NSF)',
    handle: '@NASASpaceflight',
    channelId: 'UCSUu1lih2RifWkKtDOJdsBA',
    url: 'https://www.youtube.com/channel/UCSUu1lih2RifWkKtDOJdsBA',
    focus: 'launch',
    priority: 4,
    description: 'Comprehensive coverage of spaceflight news, launches, and Starbase activities.',
  },
  {
    id: 'pbs-space-time',
    name: 'PBS Space Time',
    handle: '@pbsspacetime',
    channelId: 'UC7_gcs09iThXybpVgjHZ_7g',
    url: 'https://www.youtube.com/@pbsspacetime',
    focus: 'science',
    priority: 5,
    description: 'Deep dives into astrophysics, cosmology, and the nature of the universe.',
  },
  {
    id: 'scott-manley',
    name: 'Scott Manley',
    handle: '@ScottManley',
    channelId: 'UCxzC4EngIsMrPmbm6Nxvb-A',
    url: 'https://www.youtube.com/@scottmanley',
    focus: 'science',
    priority: 6,
    description: 'Space science and rocket engineering explained with expertise and humor.',
  },
  {
    id: 'esa',
    name: 'European Space Agency (ESA)',
    handle: '@esa',
    channelId: 'UCIBaDdAbGlFDeS33shmlD0A',
    url: 'https://www.youtube.com/@europeanspaceagency',
    focus: 'agency',
    priority: 7,
    description: 'Official ESA channel with mission updates, science, and exploration.',
  },
  {
    id: 'rocket-lab',
    name: 'Rocket Lab',
    handle: '@RocketLab',
    channelId: 'UCsWq7LZaizhIi-c-Yo_bcpw',
    url: 'https://www.youtube.com/channel/UCsWq7LZaizhIi-c-Yo_bcpw',
    focus: 'industry',
    priority: 8,
    description: 'Electron rocket launches and Neutron development updates.',
  },
  {
    id: 'fraser-cain',
    name: 'Fraser Cain (Universe Today)',
    handle: '@frasercain',
    channelId: 'UCogrSQkBJn1KF0N9I4oM7eQ',
    url: 'https://www.youtube.com/@frasercain',
    focus: 'science',
    priority: 9,
    description: 'Space news and astronomy explained by Universe Today founder.',
  },
  {
    id: 'spaceflight-now',
    name: 'Spaceflight Now',
    handle: '@SpaceflightNowVideo',
    channelId: 'UCoLdERT4-TJ82PJOHSrsZLQ',
    url: 'https://www.youtube.com/channel/UCoLdERT4-TJ82PJOHSrsZLQ',
    focus: 'launch',
    priority: 10,
    description: 'Launch coverage and spaceflight news from Spaceflight Now.',
  },
]
