export const PLANETS = [
  {
    id: "mercury",
    name: "Mercury",
    embedUrl: "https://solarsystem.nasa.gov/gltf_embed/2369/",
    lockedStatus: "locked",
    modelSrc: "/models/planets/mercury.glb",
    tagline: "Inner Planet // Extreme Temperature Swings",
    shortDescription: "Closest planet to the Sun. Small, fast, and heavily cratered.",
  },
  {
    id: "venus",
    name: "Venus",
    embedUrl: "https://solarsystem.nasa.gov/gltf_embed/2343/",
    lockedStatus: "locked",
    modelSrc: "/models/planets/venus.glb",
    tagline: "Atmosphere // High Pressure",
    shortDescription: "Hottest planet by surface temperature, wrapped in thick clouds.",
  },
  {
    id: "earth",
    name: "Earth",
    embedUrl: "https://solarsystem.nasa.gov/gltf_embed/2393/",
    lockedStatus: "locked",
    modelSrc: "/models/planets/earth.glb",
    tagline: "Home World // Life Support: Online",
    shortDescription: "Liquid water, dynamic weather, and a protective magnetic field.",
  },
  {
    id: "mars",
    name: "Mars",
    embedUrl: "https://solarsystem.nasa.gov/gltf_embed/2372/",
    lockedStatus: "live",
    modelSrc: "/models/planets/mars.glb",
    tagline: "Rover Ops // Telemetry Active",
    shortDescription: "The Red Planet—our most active surface exploration target.",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    embedUrl: "https://solarsystem.nasa.gov/gltf_embed/2375/",
    lockedStatus: "locked",
    modelSrc: "/models/planets/jupiter.glb",
    tagline: "Gas Giant // Storm Systems Detected",
    shortDescription: "Largest planet. Home to the Great Red Spot and powerful magnetosphere.",
  },
  {
    id: "saturn",
    name: "Saturn",
    embedUrl: "https://solarsystem.nasa.gov/gltf_embed/2355/",
    lockedStatus: "locked",
    modelSrc: "/models/planets/saturn.glb",
    tagline: "Ring System // Spectral Analysis",
    shortDescription: "Iconic rings and dozens of moons—Titan leads the interest list.",
  },
  {
    id: "uranus",
    name: "Uranus",
    embedUrl: "https://solarsystem.nasa.gov/gltf_embed/2344/",
    lockedStatus: "coming_soon",
    modelSrc: "/models/planets/uranus.glb",
    tagline: "Ice Giant // Axial Tilt: Extreme",
    shortDescription: "Rotates on its side. Cold, distant, and still mysterious.",
  },
  {
    id: "neptune",
    name: "Neptune",
    embedUrl: "https://solarsystem.nasa.gov/gltf_embed/2364/",
    lockedStatus: "coming_soon",
    modelSrc: "/models/planets/neptune.glb",
    tagline: "Ice Giant // Wind Speeds: High",
    shortDescription: "Deep blue world with some of the fastest winds in the solar system.",
  },
]
