-- Seed five additional learning modules for launch readiness.
-- NOTE: This assumes `learning_modules` uses Postgres text[] for list fields.

insert into public.learning_modules (
  id,
  module_type,
  title,
  description,
  tagline,
  training_type,
  track,
  level,
  estimated_minutes,
  xp_reward,
  block_count,
  block_list,
  mission_context,
  objective,
  mission_outcomes,
  tags,
  lesson_slug,
  status,
  published_at
)
values
(
  'math.launch.window-countdown',
  'stem',
  'Launch Window Countdown Solver',
  'Determine whether launch timing fits within the required window.',
  'Calculate the safest launch timing for mission alignment.',
  'Math',
  'math',
  'cadet',
  5,
  50,
  7,
  array['mission_brief','concept','instruction','question_numeric','question_short_text','checkpoint','submission_prompt'],
  'Mission Control needs to confirm whether the vehicle can launch inside a limited window. Your job is to calculate the remaining countdown time and determine if the launch can proceed.',
  'Use time-based math to determine whether the launch window remains valid.',
  array[
    'Understand what a launch window means',
    'Calculate time remaining before window close',
    'Compare countdown time against mission limits',
    'Submit a launch timing decision'
  ],
  array['launch','math','countdown','window'],
  'math.launch.window-countdown',
  'published',
  now()
),
(
  'math.lunar.oxygen-supply',
  'stem',
  'Lunar Oxygen Supply Estimator',
  'Estimate oxygen reserves for a lunar surface mission.',
  'Estimate oxygen reserves for a lunar surface mission.',
  'Math',
  'math',
  'cadet',
  6,
  60,
  7,
  array['mission_brief','concept','instruction','question_numeric','question_short_text','checkpoint','submission_prompt'],
  'A lunar surface crew must verify that their oxygen reserves can support the planned mission duration. You are assigned to calculate whether the current supply is enough for the crew.',
  'Calculate total oxygen consumption based on crew size, hourly usage, and mission duration.',
  array[
    'Calculate total oxygen demand',
    'Compare supply against demand',
    'Identify whether the reserve is safe',
    'Explain why margin matters in space missions'
  ],
  array['lunar','life-support','oxygen','math'],
  'math.lunar.oxygen-supply',
  'published',
  now()
),
(
  'science.solar.storm-shielding',
  'stem',
  'Solar Storm Shielding Decision',
  'Decide when a crew should shelter from solar radiation.',
  'Decide when a crew should shelter from solar radiation.',
  'Science',
  'science',
  'cadet',
  6,
  60,
  7,
  array['mission_brief','concept','instruction','question_numeric','question_short_text','checkpoint','submission_prompt'],
  'Space weather monitors report an increase in solar activity. The crew needs a recommendation on whether to continue normal operations or move to a shielded area.',
  'Review simplified radiation readings and determine whether the crew should enter shelter protocol.',
  array[
    'Understand basic solar storm risk',
    'Compare radiation values against a safety threshold',
    'Make a mission safety decision',
    'Explain the reasoning behind the recommendation'
  ],
  array['science','space-weather','radiation','safety'],
  'science.solar.storm-shielding',
  'published',
  now()
),
(
  'math.mars.rover-battery-budget',
  'stem',
  'Mars Rover Battery Budget',
  'Balance rover power use during a surface operation.',
  'Balance rover power use during a surface operation.',
  'Math',
  'math',
  'cadet',
  7,
  70,
  7,
  array['mission_brief','concept','instruction','question_numeric','question_short_text','checkpoint','submission_prompt'],
  'A Mars rover has limited battery capacity for a planned drive, camera scan, and communications pass. You must calculate whether the planned operation can be completed safely.',
  'Add power costs for each rover task and compare them against total available battery capacity.',
  array[
    'Estimate energy use by task',
    'Calculate remaining battery',
    'Determine if the mission plan is safe',
    'Recommend whether to proceed or reduce activity'
  ],
  array['mars','rover','power','math'],
  'math.mars.rover-battery-budget',
  'published',
  now()
),
(
  'science.orbit.debris-avoidance',
  'stem',
  'Orbital Debris Avoidance Check',
  'Assess whether a spacecraft should perform an avoidance maneuver.',
  'Assess whether a spacecraft should perform an avoidance maneuver.',
  'Science',
  'science',
  'cadet',
  7,
  70,
  7,
  array['mission_brief','concept','instruction','question_numeric','question_short_text','checkpoint','submission_prompt'],
  'Tracking data shows a piece of orbital debris passing near a spacecraft. You must compare the predicted miss distance against a safety threshold and recommend whether Command should initiate an avoidance burn.',
  'Determine if the predicted close approach is inside the danger zone.',
  array[
    'Understand close approach distance',
    'Compare risk values against a threshold',
    'Make a go/no-go maneuver recommendation',
    'Explain why debris avoidance matters'
  ],
  array['orbit','debris','safety','science'],
  'science.orbit.debris-avoidance',
  'published',
  now()
)
on conflict (id) do update set
  module_type = excluded.module_type,
  title = excluded.title,
  description = excluded.description,
  tagline = excluded.tagline,
  training_type = excluded.training_type,
  track = excluded.track,
  level = excluded.level,
  estimated_minutes = excluded.estimated_minutes,
  xp_reward = excluded.xp_reward,
  block_count = excluded.block_count,
  block_list = excluded.block_list,
  mission_context = excluded.mission_context,
  objective = excluded.objective,
  mission_outcomes = excluded.mission_outcomes,
  tags = excluded.tags,
  lesson_slug = excluded.lesson_slug,
  status = excluded.status,
  published_at = excluded.published_at;

